apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t4k-policies
  namespace: openshift-gitops
  annotations: { argocd.argoproj.io/sync-wave: "30" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/trilio-demo/acmgitops.git
    targetRevision: main
    path: components/t4k
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
    retry: { limit: 10, backoff: { duration: 30s, maxDuration: 10m, factor: 2 } }
